#!/bin/bash

TipFun(){
  pwd
  echo “$1”
  ##read -n1 -r -p "按任意键继续" key
}



create_cordova-hcp-json(){
  _now=$(date +"%Y.%m.%d-%H.%M.%S")
  touch $1
  echo "{" > $1
  echo " \"autogenerated\": true," >> $1
  echo " \"min_native_interface\":1," >> $1
  echo " \"content_url\": \"http://ohapp.railsky.com/$2/\"," >> $1
  echo " \"update\": \"now\"" >> $1
  echo "}" >> $1
}



create_WebAppName(){
  _now=$(date +"%Y.%m.%d-%H.%M.%S")
  touch $1
  echo "//该文件是系统自动生成的，代码不能在这里添加" > $1
  echo "export class WebAppName {" >> $1
  echo " static interfacecode = \"$2\";" >> $1
  echo " static appVersion = \" $_now \";" >> $1
  echo "}" >> $1
}




DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd ${DIR} || exit



TipFun "1./resourceprepare.sh $1"
cd ${DIR}
sudo chmod +x ./resourceprepare.sh
./resourceprepare.sh $1


TipFun "2.sudo yarn"
sudo yarn link 'oneheart-core'


TipFun "3.sudo cp release-signing.properties platforms/android"
cd ${DIR}
sudo cp release-signing.properties platforms/android

## cj add 20171226  为了使包里面的文件有很多是不同的
TipFun "4.remove old www file"
sudo rm -f ./www/*.* 
sudo rm -rf ./www/assets 
sudo rm -rf ./www/build
## 随机创建小的垃圾资源文件 cj test script window OK 20171226
sudo node createbadfile.js $1 


cd ${DIR} || exit
TipFun "5.sudo yarn"
#rm yarn.lock -f  #不能删除 保存各个文件的来源地址即文件的版本管理
sudo yarn
TipFun "6.sudo ionic cordova build android --release --prod"
cd ${DIR}
sudo ionic cordova build android --release --prod


TipFun "7.在项目路径下运行cordova-hcp build，生成release的补丁 运行后会在www目录下生成chcp.json和chcp.manifest文件（必须）"

cd ${DIR}

cordova-hcp build



TipFun "8.能升级的apk sudo ionic build android --release --prod"

cd ${DIR}

#sudo ionic cordova build android --prod --aot=false
sudo ionic cordova build android --release --prod
sudo ionic cordova build ios --release --prod



